"""added owner

Revision ID: 583601029dbd
Revises: ead0dc3a30a1
Create Date: 2022-06-29 13:52:43.504938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583601029dbd'
down_revision = 'ead0dc3a30a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
